name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: lab15
        run: mvn -B package

      - name: Checkstyle Шалгах
        working-directory: lab15
        run: mvn checkstyle:check

      - name: JUnit Тест ба JaCoCo Coverage Шалгах
        working-directory: lab15
        run: mvn test jacoco:check

      - name: JaCoCo Тайлан Үүсгэх
        working-directory: lab15
        run: mvn jacoco:report
